from timm.models import create_model, load_checkpoint
import os
import torch

from ours import mymodel


def load_mymodel(args, train=True, _model_name='mymodel'):
    if train:
        model = create_model(
                _model_name,
                pretrained=False,
                pretrained_cfg=None,
                pretrained_cfg_overlay=None,
                drop_rate=0.,
                drop_path_rate=0.,
                drop_block_rate=None,
                keep_ratio = args.keep_ratio,
                gating=args.gating,
                max_ratio=args.max_ratio,
                train_mode='training',
                patch_size=args.patch_size,
                embed_dim=args.embed_dim,
                num_heads=args.num_heads,
                pred_len=args.pred_len,
                seq_len=args.seq_len,
                qkv_bias=False, 
                mlp_ratios=args.mlp_ratios,
                depths=args.num_layers, 
                sr_ratios=1,
                time_num_layers=args.time_num_layers,
                c_in=args.c_in,
                bias=args.bias,
                tau=args.tau,
                perm=args.perm,
                spk_encoding=args.spk_encoding,
                use_neo_bank=getattr(args, 'use_neo_bank', False),
                neo_bank_decay=getattr(args, 'neo_bank_decay', 0.99),
                neo_bank_alpha=getattr(args, 'neo_bank_alpha', 0.1),
                neo_bank_thresh=getattr(args, 'neo_bank_thresh', 0.10),
                use_kd=getattr(args, 'use_kd', False),
                kd_head_mode=getattr(args, 'kd_head_mode', 'pooled'),
                ablate_trend=getattr(args, 'ablate_trend', False),
                lam_trend=getattr(args, 'lam_trend', 0.5),
                trend_k_ratio=getattr(args, 'trend_k_ratio', 0.25),
                ms_scales=getattr(args, 'ms_scales', 4),
                ms_fuse=getattr(args, 'ms_fuse', 'replay'),
                mca_swap=getattr(args, 'mca_swap', False),
                head_mode=getattr(args, 'head_mode', 'flatten'),
                use_pe=getattr(args, 'use_pe', False),
                use_tn_pos=getattr(args, 'use_tn_pos', False),
                neo_tau_pos=getattr(args, 'neo_tau_pos', 8.0),
                tn_ntau=getattr(args, 'tn_ntau', 1),
                mr_fusion=getattr(args, 'mr_fusion', 'attn'),
                neo_tau=getattr(args, 'neo_tau', 8.0),
                aux_membrane=getattr(args, 'aux_membrane', False),
                neo_recurrent=getattr(args, 'neo_recurrent', False),
                neo_exact=(not getattr(args, 'neo_legacy', False)),
                neo_out_residual=getattr(args, 'neo_out_residual', False),
                wrec_mode=getattr(args, 'wrec_mode', 'full'),
                mask_past=getattr(args, 'mask_past', 0),
                probe_neo=getattr(args, 'probe_neo', False),
                no_neo=getattr(args, 'no_neo', False),
                neo_plif=getattr(args, 'neo_plif', False),
                neo_control=getattr(args, 'neo_control', 'none'),
                neo_query=getattr(args, 'neo_query', 'membrane'),
                roll_mode=getattr(args, 'roll_mode', 'roll'),
                hippo_enc=getattr(args, 'hippo_enc', 'repeat'),
                hippo_boundary=getattr(args, 'hippo_boundary', 'wrap'),
                hippo_unroll=getattr(args, 'hippo_unroll', 'pre'),
                no_attn=getattr(args, 'no_attn', False),
                aux_next=getattr(args, 'aux_next', False),
                roll_boundary=getattr(args, 'roll_boundary', 'wrap'),
                neo_input=getattr(args, 'neo_input', 'patch'),
                neo_full_grad=getattr(args, 'neo_full_grad', False),
                neo_fuse=getattr(args, 'neo_fuse', 'gate_attn'),
                init_order_fix=getattr(args, 'init_order_fix', False),
                wavelet_enc=getattr(args,'wavelet_enc',False), wavelet_levels=getattr(args,'wavelet_levels',4),
                neo_stream=getattr(args,'neo_stream',False), neo_stream_input=getattr(args,'neo_stream_input','time'),
                dual_stream=getattr(args,'dual_stream',False), dual_dim=getattr(args,'dual_dim',0),
                dual_mode=getattr(args,'dual_mode','ft'),
                dual_head=getattr(args,'dual_head','f'),
                neo_recall=getattr(args,'neo_recall',False), neo_recall_gate=getattr(args,'neo_recall_gate','alpha'),
                neo_recall_tgt=getattr(args,'neo_recall_tgt','raw'),
                neo_recall_grad=getattr(args,'neo_recall_grad','stop'),
                neo_mask_ratio=getattr(args,'neo_mask_ratio',0.0),
                aux_l1=getattr(args,'aux_l1',False),
                neo_backend=getattr(args,'neo_backend','neolayer'),
                neo_xattn=getattr(args,'neo_xattn',False),
                hippo_mixer=getattr(args,'hippo_mixer','attn'),
                hf_layers=getattr(args,'hf_layers',2), hf_kernel=getattr(args,'hf_kernel',3),
                serial_mode=getattr(args,'serial_mode','off'),
                no_aux=getattr(args,'no_aux',False),
                refine_steps=getattr(args,'refine_steps',1),
                res_size=getattr(args,'res_size',256),
                res_rec_density=getattr(args,'res_rec_density',0.10),
                res_in_density=getattr(args,'res_in_density',0.10),
                res_ei_ratio=getattr(args,'res_ei_ratio',0.80),
                res_rho=getattr(args,'res_rho',0.90),
                res_in_scale=getattr(args,'res_in_scale',30.0),
                res_traces=getattr(args,'res_traces',2),
                res_wrec=getattr(args,'res_wrec','full'),
                res_readout=getattr(args,'res_readout','spike'),
                res_seed=(getattr(args,'seed',0) if getattr(args,'res_seed',-1) < 0 else args.res_seed),
                dual_attn=getattr(args,'dual_attn','cross'),
                wavelet_name=getattr(args,'wavelet_name','b3'), wavelet_mode=getattr(args,'wavelet_mode','wavelet'),
                wavelet_shuffle=getattr(args,'wavelet_shuffle',False), wavelet_neo_appr=getattr(args,'wavelet_neo_appr',True),
                neo_seq=getattr(args, 'neo_seq', 'identity'),
                neo_membrane_out=getattr(args, 'neo_membrane_out', False),
                neo_predcode=getattr(args, 'neo_predcode', False),
                neo_aux_next=getattr(args, 'neo_aux_next', False),
                no_overlap=getattr(args, 'no_overlap', False),
                neo_grad=getattr(args, 'neo_grad', 0.05),
                neo_patch_size=getattr(args, 'neo_patch_size', 32),
                xvar_mode=getattr(args, 'xvar_mode', 'A'),
                t_steps=getattr(args, 't_steps', 0),
            )
    else:
        saved_model_path = os.path.join(args.save_result_path, "model_state", f"best+model.pt")
        model = create_model(
            _model_name,
            pretrained=False,
            pretrained_cfg=None,
            pretrained_cfg_overlay=None,
            checkpoint_path=saved_model_path,
            drop_rate=0.,
            keep_ratio = args.keep_ratio,
            drop_path_rate=0.,
            drop_block_rate=None,
            gating=args.gating,
            max_ratio=args.max_ratio,
            train_mode='training',
            pred_len=args.pred_len,
            seq_len=args.seq_len,
            patch_size=args.patch_size,
            embed_dim=args.embed_dim,
            num_heads=args.num_heads,
            qkv_bias=False,
            mlp_ratios=args.mlp_ratios,
            depths=args.num_layers,
            sr_ratios=1,
            time_num_layers=args.time_num_layers,
            c_in=args.c_in,
            bias=args.bias,
            tau=args.tau,
            spk_encoding=args.spk_encoding,
            use_neo_bank=getattr(args, 'use_neo_bank', False),
            neo_bank_decay=getattr(args, 'neo_bank_decay', 0.99),
            neo_bank_alpha=getattr(args, 'neo_bank_alpha', 0.1),
            neo_bank_thresh=getattr(args, 'neo_bank_thresh', 0.10),
            use_kd=getattr(args, 'use_kd', False),
            kd_head_mode=getattr(args, 'kd_head_mode', 'pooled'),
            ablate_trend=getattr(args, 'ablate_trend', False),
            lam_trend=getattr(args, 'lam_trend', 0.5),
            trend_k_ratio=getattr(args, 'trend_k_ratio', 0.25),
            xvar_mode=getattr(args, 'xvar_mode', 'A'),
            t_steps=getattr(args, 't_steps', 0),
            # review 6.5: eval branch MUST pass the same structure-determining Neocortex args
            # as the train branch, or an active/variant checkpoint loads into a passive skeleton
            # (state_dict mismatch). Keep this list in sync with the train branch above.
            neo_tau=getattr(args, 'neo_tau', 8.0),
            neo_recurrent=getattr(args, 'neo_recurrent', False),
            neo_exact=(not getattr(args, 'neo_legacy', False)),
                neo_out_residual=getattr(args, 'neo_out_residual', False),
            wrec_mode=getattr(args, 'wrec_mode', 'full'),
            no_neo=getattr(args, 'no_neo', False),
            neo_plif=getattr(args, 'neo_plif', False),
            neo_fuse=getattr(args, 'neo_fuse', 'gate_attn'),
            init_order_fix=getattr(args, 'init_order_fix', False),
                wavelet_enc=getattr(args,'wavelet_enc',False), wavelet_levels=getattr(args,'wavelet_levels',4),
                neo_stream=getattr(args,'neo_stream',False), neo_stream_input=getattr(args,'neo_stream_input','time'),
                dual_stream=getattr(args,'dual_stream',False), dual_dim=getattr(args,'dual_dim',0),
                dual_mode=getattr(args,'dual_mode','ft'),
                dual_head=getattr(args,'dual_head','f'),
                neo_recall=getattr(args,'neo_recall',False), neo_recall_gate=getattr(args,'neo_recall_gate','alpha'),
                neo_recall_tgt=getattr(args,'neo_recall_tgt','raw'),
                neo_recall_grad=getattr(args,'neo_recall_grad','stop'),
                dual_attn=getattr(args,'dual_attn','cross'),
                wavelet_name=getattr(args,'wavelet_name','b3'), wavelet_mode=getattr(args,'wavelet_mode','wavelet'),
                wavelet_shuffle=getattr(args,'wavelet_shuffle',False), wavelet_neo_appr=getattr(args,'wavelet_neo_appr',True),
            neo_membrane_out=getattr(args, 'neo_membrane_out', False),
            neo_predcode=getattr(args, 'neo_predcode', False),
            aux_membrane=getattr(args, 'aux_membrane', False),
            use_pe=getattr(args, 'use_pe', False),
            head_mode=getattr(args, 'head_mode', 'flatten'),
            mr_fusion=getattr(args, 'mr_fusion', 'attn'),
        )

        model = model.to(args.device)
        model.train_mode = 'testing'
        model.init_testing()
        print(f"{args.model} was successfully loaded. (epoch = {args.saved_epoch[-1]:03d})")

    return model



LOAD_MODEL = {
    "myModel": load_mymodel,
}
